package re

var tests = []struct {
	re      string
	tokens  []token
	root    *node
	input   string
	matches []string
}{
	{"a",
		[]token{
			{val: 'a', tp: char},
			{val: eof, tp: end},
		},
		&node{
			set: NewSet("a", false),
			tp:  set,
		},
		"abAbaa",
		[]string{"a", "a", "a"},
	},
	{"(a)",
		[]token{
			{val: '(', tp: ope},
			{val: 'a', tp: char},
			{val: ')', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			set: NewSet("a", false),
			tp:  set,
		},
		"a",
		[]string{"a"},
	},
	{"abc",
		[]token{
			{val: 'a', tp: char},
			{val: 'b', tp: char},
			{val: 'c', tp: char},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{set: NewSet("b", false), tp: set},
				{set: NewSet("c", false), tp: set},
			},
		},
		"aaaaaabcaaabac",
		[]string{"abc"},
	},
	{`\s\t\n`,
		[]token{
			{val: ' ', tp: char},
			{val: '\t', tp: char},
			{val: '\n', tp: char},
			{val: eof, tp: end},
		},

		&node{
			tp: and,
			children: []*node{
				{set: NewSet(" ", false), tp: set},
				{set: NewSet("\t", false), tp: set},
				{set: NewSet("\n", false), tp: set},
			},
		},
		"aaaa\ta\n aaa \t\n",
		[]string{" \t\n"},
	},
	{"a|b|c",
		[]token{
			{val: 'a', tp: char},
			{val: '|', tp: ope},
			{val: 'b', tp: char},
			{val: '|', tp: ope},
			{val: 'c', tp: char},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{set: NewSet("b", false), tp: set},
				{set: NewSet("c", false), tp: set},
			},
		},
		"azzzbczzzbza",
		[]string{"a", "b", "c", "b", "a"},
	},
	{"ab|ac",
		[]token{
			{val: 'a', tp: char},
			{val: 'b', tp: char},
			{val: '|', tp: ope},
			{val: 'a', tp: char},
			{val: 'c', tp: char},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{
					tp: and,
					children: []*node{
						{set: NewSet("a", false), tp: set},
						{set: NewSet("b", false), tp: set},
					},
				},
				{
					tp: and,
					children: []*node{
						{set: NewSet("a", false), tp: set},
						{set: NewSet("c", false), tp: set},
					},
				},
			},
		},
		"abacacbaaab",
		[]string{"ab", "ac", "ac", "ab"},
	},
	{"a*", []token{
		{val: 'a', tp: char},
		{val: '*', tp: ope},
		{val: eof, tp: end},
	},
		&node{
			tp: star,
			children: []*node{
				{set: NewSet("a", false), tp: set},
			},
		},
		"aaaabc",
		[]string{"aaaa", "", ""},
	},
	{"ab*",
		[]token{
			{val: 'a', tp: char},
			{val: 'b', tp: char},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet("b", false), tp: set},
					},
				},
			},
		},
		"aabbabaaa",
		[]string{"aab", "ab", "aaa"},
	},
	{"a*b*",
		[]token{
			{val: 'a', tp: char},
			{val: '*', tp: ope},
			{val: 'b', tp: char},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{
					tp: star,
					children: []*node{
						{set: NewSet("a", false), tp: set},
					},
				},
				{
					tp: star,
					children: []*node{
						{set: NewSet("b", false), tp: set},
					},
				},
			},
		},
		"aabbabaaa",
		[]string{"aabb", "ab", "aaa"},
	},
	{"a|b*",
		[]token{
			{val: 'a', tp: char},
			{val: '|', tp: ope},
			{val: 'b', tp: char},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet("b", false), tp: set},
					},
				},
			},
		},
		"aabbabaaa",
		[]string{"a", "a", "bb", "a", "b", "a", "a", "a"},
	},
	{"(a|b)*|c", []token{
		{val: '(', tp: ope},
		{val: 'a', tp: char},
		{val: '|', tp: ope},
		{val: 'b', tp: char},
		{val: ')', tp: ope},
		{val: '*', tp: ope},
		{val: '|', tp: ope},
		{val: 'c', tp: char},
		{val: eof, tp: end},
	},
		&node{
			tp: or,
			children: []*node{
				{
					tp: star,
					children: []*node{
						{
							tp: or,
							children: []*node{
								{set: NewSet("a", false), tp: set},
								{set: NewSet("b", false), tp: set},
							},
						},
					},
				},
				{set: NewSet("c", false), tp: set},
			},
		},
		"acaacbbcbcc",
		[]string{"a", "c", "aa", "c", "bb", "c", "b", "c", "c"},
	},
	{"[a-z]",
		[]token{
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: eof, tp: end},
		},
		&node{set: NewSet("abcdefghijklmnopqrstuvwxyz", false), tp: set},
		"abcdZABC",
		[]string{"a", "b", "c", "d"},
	},
	{`[\t\n\s]`,
		[]token{
			{val: '[', tp: ope},
			{val: '\t', tp: char},
			{val: '\n', tp: char},
			{val: ' ', tp: char},
			{val: ']', tp: ope},
			{val: eof, tp: end},
		},
		&node{set: NewSet("\n\t ", false), tp: set},
		"aaaa\taaaa\n a a \n",
		[]string{"\t", "\n", " ", " ", " ", "\n"},
	},
	{"[a-z]|[A-Z]",
		[]token{
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: '|', tp: ope},
			{val: '[', tp: ope},
			{val: 'A', tp: char},
			{val: '-', tp: ope},
			{val: 'Z', tp: char},
			{val: ']', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("abcdefghijklmnopqrstuvwxyz", false), tp: set},
				{set: NewSet("ABCDEFGHIJKLMNOPQRSTUVWXYZ", false), tp: set},
			},
		},
		"aAbBcC",
		[]string{"a", "A", "b", "B", "c", "C"},
	},
	{"[A-Z][a-z]*",
		[]token{
			{val: '[', tp: ope},
			{val: 'A', tp: char},
			{val: '-', tp: ope},
			{val: 'Z', tp: char},
			{val: ']', tp: ope},
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("ABCDEFGHIJKLMNOPQRSTUVWXYZ", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet("abcdefghijklmnopqrstuvwxyz", false), tp: set},
					},
				},
			},
		},
		"aAbBcC",
		[]string{"a", "A", "b", "B", "c", "C"},
	},
	{`\s[a-z ]*`,
		[]token{
			{val: ' ', tp: char},
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ' ', tp: char},
			{val: ']', tp: ope},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet(" ", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet(" abcdefghijklmnopqrstuvwxyz", false), tp: set},
					},
				},
			},
		},
		"  abc , abc a",
		[]string{"  abc ", " abc a"},
	},
	{"(a)|(c)",
		[]token{
			{val: '(', tp: ope},
			{val: 'a', tp: char},
			{val: ')', tp: ope},
			{val: '|', tp: ope},
			{val: '(', tp: ope},
			{val: 'c', tp: char},
			{val: ')', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{set: NewSet("c", false), tp: set},
			},
		},
		"aaacc",
		[]string{"a", "a", "a", "c", "c"},
	},
	{"a[^a-z]*",
		[]token{
			{val: 'a', tp: char},
			{val: '[', tp: ope},
			{val: '^', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet("abcdefghijklmnopqrstuvwxyzc", true), tp: set},
					},
				},
			},
		},
		"aaaZZZ",
		[]string{"a", "a", "aZZZ"},
	},
	{`a[a-z^]*`,
		[]token{
			{val: 'a', tp: char},
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: '^', tp: char},
			{val: ']', tp: ope},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{
					tp: star,
					children: []*node{
						{set: NewSet("^abcdefghijklmnopqrstuvwxyz", false), tp: set},
					},
				},
			},
		},
		"aaaZZZ^^",
		[]string{"a", "a", "aZZZ^^"},
	},
	{`a|\e`,
		[]token{
			{val: 'a', tp: char},
			{val: '|', tp: ope},
			{val: 0, tp: empty},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{tp: emptyStr},
			},
		},
		"abbaab",
		[]string{"a", "", "", "a", "a", ""},
	},
	{`a|[]`,
		[]token{
			{val: 'a', tp: char},
			{val: '|', tp: ope},
			{val: '[', tp: ope},
			{val: ']', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: or,
			children: []*node{
				{set: NewSet("a", false), tp: set},
				{set: NewSet("", false), tp: set},
			},
		},
		"abbaab",
		[]string{"a", "a", "a"},
	},
	{`[a-z]*\s\*`,
		[]token{
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: '*', tp: ope},
			{val: ' ', tp: char},
			{val: '*', tp: char},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{
					tp: star,
					children: []*node{
						{set: NewSet("abcdefghijklmnopqrstuvwxyz", false), tp: set},
					},
				},
				{set: NewSet(" ", false), tp: set},
				{set: NewSet("*", false), tp: set},
			},
		},
		" *ab *baab",
		[]string{" *", "ab *"},
	},
	{"([A-Z]|[a-z])*",
		[]token{
			{val: '(', tp: ope},
			{val: '[', tp: ope},
			{val: 'A', tp: char},
			{val: '-', tp: ope},
			{val: 'Z', tp: char},
			{val: ']', tp: ope},
			{val: '|', tp: ope},
			{val: '[', tp: ope},
			{val: 'a', tp: char},
			{val: '-', tp: ope},
			{val: 'z', tp: char},
			{val: ']', tp: ope},
			{val: ')', tp: ope},
			{val: '*', tp: ope},
			{val: eof, tp: end},
		},
		&node{
			tp: star,
			children: []*node{
				{
					tp: or,
					children: []*node{
						{set: NewSet("ABCDEFGHIJKLMNOPQRSTUVWXYZ", false), tp: set},
						{set: NewSet("abcdefghijklmnopqrstuvwxyz", false), tp: set},
					},
				},
			},
		},
		"AaBbCc_+,",
		[]string{"A", "a", "B", "b", "C", "c"},
	},
	{"\uFFFF",
		[]token{
			{val: '\uFFFF', tp: char},
			{val: eof, tp: end},
		},
		&node{
			set: NewSet("\uFFFF", false),
			tp:  set,
		},
		"\uFFFFabc",
		[]string{"\uFFFF"},
	},
	{"\uFFFF[\u0000-\u0004]", []token{
		{val: '\uFFFF', tp: char},
		{val: '[', tp: ope},
		{val: '\u0000', tp: char},
		{val: '-', tp: ope},
		{val: '\u0004', tp: char},
		{val: ']', tp: ope},
		{val: eof, tp: end},
	},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("\uFFFF", false), tp: set},
				{set: NewSet("\u0000\u0001\u0002\u0003\u0004", false), tp: set},
			},
		},
		"\uFFFF\u0003abc",
		[]string{"\uFFFF\u0003"},
	},
	{"\uFFFF\\s",
		[]token{
			{val: '\uFFFF', tp: char},
			{val: ' ', tp: char},
			{val: eof, tp: end},
		},
		&node{
			tp: and,
			children: []*node{
				{set: NewSet("\uFFFF", false), tp: set},
				{set: NewSet(" ", false), tp: set},
			},
		},
		"\uFFFF abc",
		[]string{"\uFFFF "},
	},
}
